### ISSUE TITLE
make CVs parallelizable

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/osprey#141]
As well as allow for more shuffle-split iterations, this would also allow LOO/LKO for large datasets to be done in a reasonable about of time. 

note: LOO is not appropriate for MSMs, but LKO might be?

cc @mpharrigan @brookehus

**Comment by msultan** [comment]
I wonder, given that we already have multiple workers making different models on a single machine, if we have more parrallelization that it will lead to collisions and actually slow things down.

**Comment by cxhernandez** [comment]
How is this different than doing a bunch of 1-CV jobs?

**Comment by msultan** [comment]
Currently, i might have 16 workers doing 5-fold CV using various hyperparams. Each worker gets one core so i am afraid if we parallelize this, each worker starts trying to use other cores which slows down the models for everyone. There might be a intelligent way to handle this, i just wanted to raise this as an issue since the workers dont communicate between each other(only to the db).

**Comment by cxhernandez** [comment]
not parallelizing within a worker... parallelizing across jobs

**Comment by cxhernandez** [comment]
done in #231
